---
- name: Test connectivity on localhost
  hosts: all
  become: true        # <-- Add this to run tasks with sudo
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable nginx service
      service:
        name: nginx
        state: started
        enabled: true
