---
- name: copying file to remote
  hosts: all
 
  tasks: 
   - name: copy files
     copy:
       src: /home/ubuntu/ansible-playbooks/hello.txt
       dest: /home/ubuntu
       owner: ubuntu
       mode: 0777
       backup: true
