---
- name: set password
  hosts: all
  become: true

  tasks:
   - name: set password
     user: 
      name: nitin
      update_password: always
      password: "{{'abcd123' | password_hash('sha512')}}"
